---
- name: zephyr base worker setup
  hosts: all
  become: true
  become_user: root
  
  vars: 
    pkgslist:
      - git
      - cmake 
      - ninja-build
      - gperf 
      - ccache
      - dfu-util 
      - device-tree-compiler
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-tk
      - python3-wheel
      - xz-utils
      - file
      - libpython3.8-dev
      - make
      - gcc
      - gcc-multilib
      - g++-multilib
      - libsdl2-dev
      - libmagic1
      - udev
      - python3-venv

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
  - name: create zephyr inventory
    ansible.builtin.file:
      path: /tmp/zephyr
      state: directory

  - name: apt update 
    ansible.builtin.apt:
      update_cache: yes

  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: safe

  - name: installing wget with apt
    ansible.builtin.apt:
      name: wget
      state: latest

  - name: installing packages with apt
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      allow_downgrade: yes
      install_recommends: false
    loop: "{{ pkgslist }}"

  - name: wget kitware
    ansible.builtin.shell: "wget -O /tmp/zephyr/kitware-archive.sh https://apt.kitware.com/kitware-archive.sh"

  - name: run kitware-archive.sh
    ansible.builtin.shell: "bash /tmp/zephyr/kitware-archive.sh"

  - name: check versions of installed python, cmake and dtc
    ansible.builtin.command: "{{ item }}"
    register: check_versions_output
    loop:
      - "cmake --version"
      - "python3 --version"
      - "dtc --version"

  - name: echo output of installed versions of python, cmake and dtc
    ansible.builtin.shell: "echo {{ check_versions_output }}"

  - name: install docutils and west with pip
    ansible.builtin.shell: python3 -m pip install west docutils==0.18

  - name: export path
    ansible.builtin.shell: echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc

  - name: get zephyr repo, update west and install requirements with pip
    ansible.builtin.shell: |
      . ~/.bashrc && \
      west init /tmp/zephyr/zephyrproject && \ 
      cd /tmp/zephyr/zephyrproject && \
      west update && \ 
      west zephyr-export && \
      python3 -m pip install -r /tmp/zephyr/zephyrproject/zephyr/scripts/requirements.txt

  - name: wget zephyr sdk
    ansible.builtin.shell: |
      wget -O /tmp/zephyr/zephyr-sdk-0.16.1_linux-x86_64.tar.xz https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/zephyr-sdk-0.16.1_linux-x86_64.tar.xz
  
  - name: wget zephyr project rts
    ansible.builtin.shell: |
      cd /tmp/zephyr && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.1/sha256.sum | shasum --check --ignore-missing
  - name: untar zephyr-sdk 
    ansible.builtin.shell: cd /tmp/zephyr && tar xvf zephyr-sdk-0.16.1_linux-x86_64.tar.xz -C /opt

  - name: install zephyr-sdk
    ansible.builtin.shell: cd /opt/zephyr-sdk-0.16.1 && bash setup.sh -h
