name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Build docker image using Dockerfile
  - run: docker build . -t redxm-x/devops-stuff 